# Swagger/OpenAPI documentation for the blog API
# This file describes the API endpoints, request/response formats, and security requirements.

openapi: 3.0.3
info:
  title: Blog API
  version: 1.0.0
  description: API documentation for the blog platform

servers:
  - url: http://localhost:5000/api/v1

paths:
  /admin:
    $ref: './paths/admin.yaml'
  /users:
    $ref: './paths/users.yaml'
  /posts:
    $ref: './paths/posts.yaml'

components:
  securitySchemes:
    bearerAuth:
      $ref: './components/security/BearerAuth.yaml'
  schemas:
    User:
      $ref: './components/schemas/User.yaml'
    Post:
      $ref: './components/schemas/Post.yaml'
  responses:
    ErrorResponse:
      $ref: './components/responses/ErrorResponse.yaml'
    SuccessResponse:
      $ref: './components/responses/SuccessResponse.yaml'
