# docker-compose.yaml

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
      - redis
    env_file:
      - .env
    command: >
      sh -c "node src/utils/seed-admin.js && node src/server.js"
    networks:
      - backend

  mongo_db:
    image: mongo:6
    container_name: blog_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    networks:
      - backend

  redis:
    image: redis:6
    container_name: blog_redis_cache
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mongo_db:

networks:
  backend:
    driver: bridge