version: "3.9"

services:
  api:
    build: .
    container_name: blog-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/blogDB
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: blog-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6
    container_name: blog-redis-cache
    ports:
      - "6379:6379"

volumes:
  mongo-data: