# docker-compose.yaml

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    restart: always

  mongo:
    image: mongo:6
    container_name: blog-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6
    container_name: blog-redis-cache
    ports:
      - "6379:6379"

volumes:
  mongo-data:
