# Swagger/OpenAPI documentation for the blog API
# This file describes the API endpoints, request/response formats, and security requirements.

openapi: 3.0.3
info:
  title: Blog API
  version: 1.0.0
  description: API documentation for the blog platform

servers:
  - url: http://localhost:5000/api/v1

paths:
  /admin:
    $ref: "./components/schemas/User.yaml"
  
  /users/register:
    $ref: "./routes/users/register.yaml"

  /posts:
    $ref: './paths/Posts.yaml'

components:
  securitySchemes:
    bearerAuth:
      $ref: './components/security/securitySchemes/BearerAuth.yaml'
  schemas:
    User:
      $ref: './components/schemas/User.yaml'
    Post:
      $ref: './components/schemas/Post.yaml'
    Like:
      $ref: './components/schemas/Like.yaml'
    Comment:
      $ref: './components/schemas/Comment.yaml'
  responses:
    ErrorResponse:
      $ref: './components/responses/ErrorResponse.yaml'
    SuccessResponse:
      $ref: './components/responses/SuccessResponse.yaml'
