# Swagger/OpenAPI documentation for the blog API
# This file describes the API endpoints, request/response formats, and security requirements.

openapi: 3.0.0
info:
  title: Blog API
  version: 1.0.0
  description: API documentation for the blog platform

servers:
  - url: http://localhost:4001

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /api/admin/users/{id}/role:
    patch:
      summary: Update a user's role
      tags: [Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [user, author, admin]
              required:
                - role
            example:
              role: author
      responses:
        200:
          description: Success
        400:
          description: Validation error
        404:
          description: User not found
        401:
          description: Unauthorized
        403:
          description: Forbidden
