name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  docker:
    name: Docker
    uses: ./.github/workflows/docker.yml
